### ISSUE TITLE
启动参数 -server 与 -conf 冲突

### ISSUE THREAD

**Issue by jiejiecn** [jkstack/smartagent#3]
客户端启动参数 -server 指定服务器地址被 -conf 参数指定的配置文件覆盖，导致报错

![smartagent-client](https://user-images.githubusercontent.com/11746870/167752470-3955903d-b09f-4f93-8753-60fcac993e7c.PNG)

**Comment by lwch** [comment]
-server参数仅在reset时有效用于重置默认配置中的服务器地址，实际启动时所有配置以配置文件为准

**Comment by jiejiecn** [comment]
那就更新输出的说明，阐明 -server参数必须与 -action reset同时使用

**Comment by lwch** [comment]
fixed: 40392e9e6ea6c2bdcc8d8199cb4d7ebabea930cb
